service: aws-nodejs # NOTE: update this with your service name

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  env:
    LUMIGO_DEBUG: TRUE


functions:
  test-function:
    handler: index.handler
